# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrackets < Formula
  desc "Terminal bracket viewer for Wrackets tournaments"
  homepage "https://github.com/belvederelabs/wrackets"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belvederelabs/wrackets/releases/download/v0.1.0/wrackets_darwin_amd64.tar.gz"
      sha256 "8659a7ac2e6540bb7a8e769d11e32a39e5c97ceff39301a7d2032013376f4bbc"

      define_method(:install) do
        bin.install "wrackets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belvederelabs/wrackets/releases/download/v0.1.0/wrackets_darwin_arm64.tar.gz"
      sha256 "13d85b785b7c1fcdcba131986ae1de3f7a9d29ad04d339f7e10c7287a509dee0"

      define_method(:install) do
        bin.install "wrackets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belvederelabs/wrackets/releases/download/v0.1.0/wrackets_linux_amd64.tar.gz"
      sha256 "e16495fb7a0269fe9d032a673d0f13bb1f2376c33c19eddbecdc9e92d6c3fa2c"
      define_method(:install) do
        bin.install "wrackets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belvederelabs/wrackets/releases/download/v0.1.0/wrackets_linux_arm64.tar.gz"
      sha256 "ed75b09efc355b7208e8a74ccb94c68cf886a55948f3c8791bf016e458ec7ff4"
      define_method(:install) do
        bin.install "wrackets"
      end
    end
  end
end
