# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrackets < Formula
  desc "Tournament brackets in your terminal — local files, no accounts"
  homepage "https://github.com/belvederelabs/wrackets-releases"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belvederelabs/wrackets-releases/releases/download/v0.2.0/wrackets_darwin_amd64.tar.gz"
      sha256 "fd51b4a318f8665498cc750f656ac50ea35b0f308b2a5eab0b60a14fbe85ce88"

      define_method(:install) do
        bin.install "wrackets"
        generate_completions_from_executable(bin/"wrackets", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belvederelabs/wrackets-releases/releases/download/v0.2.0/wrackets_darwin_arm64.tar.gz"
      sha256 "9750bede17509db38d5aa393cca938c84e8cf670799c9cdbcd41112e459a99fd"

      define_method(:install) do
        bin.install "wrackets"
        generate_completions_from_executable(bin/"wrackets", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belvederelabs/wrackets-releases/releases/download/v0.2.0/wrackets_linux_amd64.tar.gz"
      sha256 "e0546b7f6b96a264a67608b67b8db2f5db6beac5dad7b3b9fefb011bfffaebd5"
      define_method(:install) do
        bin.install "wrackets"
        generate_completions_from_executable(bin/"wrackets", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belvederelabs/wrackets-releases/releases/download/v0.2.0/wrackets_linux_arm64.tar.gz"
      sha256 "c5222df2a9b7a6ef23263fa2d4dc4cef1e2607fbc5fff3a7dca8dd4d293655d3"
      define_method(:install) do
        bin.install "wrackets"
        generate_completions_from_executable(bin/"wrackets", "completion")
      end
    end
  end

  test do
    system "#{bin}/wrackets", "--version"
  end
end
